[build]
  publish = "."
  command = "echo 'No build needed'"

[[redirects]]
  from = "/about.html"
  to = "/program.html"
  status = 301
  force = true

[[redirects]]
  from = "/checkout.html"
  to = "/program.html"
  status = 301
  force = true

[[redirects]]
  from = "/invite.html"
  to = "/program.html"
  status = 301
  force = true 